### ISSUE TITLE
Mark as auto generated to avoid StyleCop violations

### ISSUE THREAD

**Issue by philippdolder** [adamralph/liteguard#137]
When I install the LiteGuard.Source package I get StyleCop violations because the code does not comply with my StyleCop settings.

I believe the `Guard.cs` should have the `<auto-generated />` marker in the header, as for my project this is considered auto-generated code.

EDIT: the suggested proposal to adjust the source code is a no-go with the Nuget 3.x, as it does no longer add the code to the repository, but adds it at compile-time from the package

**Comment by adamralph** [comment]
@philippdolder thanks for raising this.

When you say "NuGet 3.x" do you actually mean "project.json"? As I understand it, NuGet 3.x performs source package restoration for both `packages.config` (the files are transformed at install time and the results are added to the project) and for `project.json` (the files are transformed at compile time into the `obj` folder and compiled from there).

Coincidentally, [I observed this problem myself](https://ci.appveyor.com/project/adamralph/xbehave-net/build/682) just yesterday in the `project.json` case:

> C:\projects\xbehave-net\src\Xbehave.Execution\obj\Release\net45\Guard.cs.pp(1,1): warning SA1633: The file header is missing or not located at the top of the file.

I couldn't think of a way to fix it, but your proposal might just work. Are you using the classic StyleCop or StyleCop.Analyzers? I'm gradually switching everything over to the latter, as in the example build above, but I'm not sure if it respects `<auto-generated />`?

**Comment by adamralph** [comment]
It looks like [StyleCop.Analyzers does respect the comment](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/0325dd1f36e674ca91115b5f782c55336244a723/documentation/SA1633.md)

> A file that is completely auto-generated by a tool, and which should not be checked or enforced by StyleCop, can include an "auto-generated" header rather than the standard file header. This will cause StyleCop to ignore the file. This type of header should never be placed on top of a manually written code file.

**Comment by philippdolder** [comment]
@adamralph yes, I'm referring to the `project.json` way

I'm working with the StyleCop.Analyzers tooling. according to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2195 and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2108 this should work.

I quickly changed it in the code which is in the `obj` folder and the warning didn't show up
