### ISSUE TITLE
Error with generic type argument

### ISSUE THREAD

**Issue by jotatoledo** [adamralph/liteguard#202]
When trying to use `Guard.AgainstNullArgument` on a generic type argument, Im getting the following error:

> The type 'TChannel' must be a reference type in order to use it as parameter 'TArgument' in the generic type or method 'Guard.AgainstNullArgument<TArgument>(string, TArgument)'

The problem arises in the following snippet:

````csharp
public sealed class ChannelDisposer<TChannel> : IDisposable
        where TChannel :  IChannel
    {
        private TChannel innerChanel;
        private bool disposedValue = false; // To detect redundant calls

        public ChannelDisposer(TChannel channel)
        {
            Guard.AgainstNullArgument<TChannel>(nameof(channel), channel);

            this.innerChanel = channel;
        }	

....
}
````

Naturally, if I add the `class `restriction to the type argument, the error is gone. But this feels kinda cumbersome.

Related: https://github.com/adamralph/liteguard/issues/2

**Comment by adamralph** [comment]
@jotatoledo can you provide any more detail? 😄

**Comment by jotatoledo** [comment]
@adamralph updated, I pressed enter to soon while creating the issue 😄

**Comment by adamralph** [comment]
@jotatoledo thanks for the detail. Try `Guard.AgainstNullArgumentIfNullable()` instead.
