### ISSUE TITLE
How to use LiteGuard.Source?

### ISSUE THREAD

**Issue by thomasgalliker** [adamralph/liteguard#255]
Hi @adamralph, I tried to install LiteGuard.Source in a netstandard1.0 library project but it doesnt link/copy the Guard.cs file(s) to my library. What am I doing wrong? The csproj looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteGuard.Source" Version="2.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>

```

**Comment by thomasgalliker** [comment]
Okay, I think I got it: When I install the LiteGuard.Source nuget, it automatically add the source files to my library (I just don't see them in visual studio, correct?)

**Comment by adamralph** [comment]
@thomasgalliker that's correct. You will not see the source files in the Visual Studio Solution Explorer. But after installing LiteGuard.Source, you should be able to use the API immediately, and you will get Intellisense. E.g. `Guard.AgainstNullArgument(...`

**Comment by thomasgalliker** [comment]
Cool, thanks.
