### ISSUE TITLE
LiteGuard.Source doesn't work in WPF .NET Core project

### ISSUE THREAD

**Issue by stephendrew** [adamralph/liteguard#345]
## Version(s)

LiteGuard.Source 2.2.0
Microsoft Visual Studio Enterprise 2019 Version 16.7.3
.NET Core 3.1.402

## To reproduce

Create a WPF .NET Core app.  Add LiteGuard.Source.  Use `Guard.AgainstNullArgument` somewhere in MainWindow.  Project doesn't build.

## Expected behavior

Expect to behave as per a standard .NET Core app and build.

## Actual behaviour

As above.

## Workarounds

N/A

**Comment by adamralph** [comment]
Thanks for raising this @stephendrew. I'll look into it ASAP.

**Comment by adamralph** [comment]
@stephendrew this is a general problem with WPF .NET Core App projects and NuGet source packages. It is not specific to LiteGuard.Source. I've confirmed this by installing [LibLog](https://www.nuget.org/packages/LibLog), and I get the same problem there:

> error CS0246: The type or namespace name 'Logging' could not be found (are you missing a using directive or an assembly reference?)

I'm afraid you'll have to follow up on this with someone from the .NET team. There is nothing that can be done in LiteGuard to solve it.

**Comment by adamralph** [comment]
BTW @stephendrew, there's really no need to use LiteGuard.Source in an app. You'd better off using LiteGuard (the binary package).

LiteGuard.Source is really designed for libraries, so that they don't have to pull in a transitive dependency. LiteGuard (the binary package) is designed for apps.

**Comment by stephendrew** [comment]
Thanks @adamralph.

I've actually raised a ticket about this in wpf already.

I have a similar project to yours which is used in libraries and apps, and have encountered the same issue.  I found your project and wondered if you'd solved the problem :)  I thought I'd raise the issue here in case you hadn't seen it.

**Comment by adamralph** [comment]
> I've actually raised a ticket about this in wpf already.

@stephendrew is there a public URL?

**Comment by stephendrew** [comment]
https://github.com/dotnet/wpf/issues/3495
