### ISSUE TITLE
Hide Guard methods from stack trace

### ISSUE THREAD

**Issue by adamralph** [adamralph/liteguard#43]
See http://stackoverflow.com/a/11898531/49241

**Comment by urig** [comment]
@adamralph how does the SO answers help here? They require either a custom exception class or the invocation of a bespoke method for getting the stack trace. Neither of these seem relevant to LiteGuard...?

**Comment by adamralph** [comment]
@urig it's so long ago that I honestly have no idea. Perhaps this isn't even possible. 🤔

**Comment by adamralph** [comment]
Low ROI. It's one extra line in the stack trace.
